name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-analyze:
    name: Backend + Frontend Tests & SonarCloud
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Setup Java (for Sonar scanner)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Typecheck backend
        working-directory: backend
        run: npm run typecheck

      - name: Test backend with coverage
        working-directory: backend
        run: npm run test:ci

      - name: Install frontend dependencies (workaround optional deps)
        working-directory: frontend
        run: |
          npm pkg set scripts.prepare="echo skip-prepare-in-ci"
          npm install --ignore-scripts

      - name: Test frontend with coverage (Vitest)
        working-directory: frontend
        env:
          # Force rollup to use JS implementation instead of native optional binary
          ROLLUP_SKIP_NODEJS_NATIVE: true
          # also bypass postinstall in case any tool tries to run it implicitly
          NPM_CONFIG_IGNORE_SCRIPTS: true
        run: npm run coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-all
          path: |
            backend/coverage/**
            frontend/coverage-unit/**
          if-no-files-found: warn
          retention-days: 7

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.projectVersion=${{ github.run_number }}


