name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-analyze:
    name: Backend  & SonarCloud
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Setup Java (for Sonar scanner)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Typecheck backend
        working-directory: backend
        run: npm run typecheck

      - name: Test backend with coverage
        working-directory: backend
        run: npm run test:ci

      - name: Install frontend dependencies (run scripts except app postinstall)
        working-directory: frontend
        run: |
          npm pkg set scripts.postinstall="echo skip-postinstall-in-ci"
          npm ci --no-audit --no-fund

      - name: Stub Quasar tsconfig for Vitest
        working-directory: frontend
        run: |
          mkdir -p .quasar
          printf '{\n  "compilerOptions": {\n    "paths": {},\n    "types": []\n  }\n}\n' > .quasar/tsconfig.json
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.projectVersion=${{ github.run_number }}


