name: Code Quality Analysis

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run ESLint
      working-directory: ./backend
      run: npm run lint

    - name: Run Prettier check
      working-directory: ./backend
      run: npm run format -- --check

    - name: TypeScript compilation check
      working-directory: ./backend
      run: npm run build

    - name: Security audit
      working-directory: ./backend
      run: npm audit --audit-level moderate

    - name: Check for vulnerabilities
      working-directory: ./backend
      run: |
        if [ $(npm audit --audit-level high --json | jq '.metadata.vulnerabilities.high // 0') -gt 0 ]; then
          echo "High severity vulnerabilities found!"
          exit 1
        fi

    - name: Generate coverage report
      working-directory: ./backend
      run: |
        if [ -f "package.json" ] && grep -q "test:coverage" package.json; then
          npm run test:coverage
        else
          echo "No coverage script found, skipping coverage report"
        fi

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        directory: ./backend/coverage
        flags: backend
        name: backend-coverage
