name: Database Migration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/prisma/**'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Generate Prisma client
      working-directory: ./backend
      run: npm run db:generate

    - name: Run database migration
      working-directory: ./backend
      run: npm run db:push
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}

    - name: Verify migration
      working-directory: ./backend
      run: npm run db:studio -- --browser none
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
