name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Build application
      working-directory: ./backend
      run: npm run build
    
    - name: Run database migrations
      working-directory: ./backend
      run: npm run db:migrate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    - name: Deploy to production server
      run: |
        echo "Deploying to production..."
        echo "This would typically include:"
        echo "- Uploading files to server"
        echo "- Restarting services"
        echo "- Health checks"
        echo "- Rollback capability"
    
    - name: Run health check
      run: |
        echo "Running health checks..."
        echo "This would typically include:"
        echo "- API endpoint health checks"
        echo "- Database connectivity"
        echo "- External service checks"
