name: Backend - Tests and SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install dependencies (backend)
        run: npm ci

      - name: Run tests with coverage (enforce >=80% lines/functions/statements)
        env:
          NODE_ENV: test
        run: npm run test:ci

      - name: SonarCloud Scan (backend only)
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: .
          args: >-
            -Dsonar.projectKey=BorgesLeonardo_CatolicaSC-Portfolio
            -Dsonar.organization=catolicasc-portfolio
            -Dsonar.sources=backend/src
            -Dsonar.tests=backend/src/test
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
            -Dsonar.typescript.lcov.reportPaths=backend/coverage/lcov.info
            -Dsonar.typescript.tsconfigPaths=backend/tsconfig.json
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.newCode.period=previous_version


