name: SonarQube Quality Gate

on:
  workflow_run:
    workflows: ["Build and SonarQube Analysis"]
    types:
      - completed

jobs:
  sonarqube-quality-gate:
    name: SonarQube Quality Gate
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5
